# Generated by Django 3.1.7 on 2021-06-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospital_head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(default='0', max_length=50)),
                ('password', models.CharField(default='0', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='admin',
        ),
    ]
