# Generated by Django 3.1.7 on 2021-06-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0004_auto_20210618_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(default='0', upload_to='media/photo'),
        ),
    ]
