# Generated by Django 3.1.7 on 2021-06-20 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0007_auto_20210620_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_register',
            old_name='doctor_name',
            new_name='dname',
        ),
        migrations.RemoveField(
            model_name='doctor_register',
            name='doctors',
        ),
    ]
