# Generated by Django 3.1.7 on 2021-06-20 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0009_auto_20210620_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_register',
            old_name='name',
            new_name='dname',
        ),
    ]
