# Generated by Django 3.1.7 on 2021-06-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0010_auto_20210620_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_register',
            old_name='dname',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='doctor_register',
            name='doctors',
            field=models.FileField(default='0', upload_to='media/doctors'),
        ),
    ]
