# Generated by Django 3.1.7 on 2021-06-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0011_auto_20210620_2011'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='doctor_register',
            new_name='doctor',
        ),
    ]
