# Generated by Django 3.1.7 on 2021-06-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0012_auto_20210620_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.CharField(default='0', max_length=25),
        ),
    ]
