# Generated by Django 3.1.7 on 2021-06-23 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mywebsite', '0015_auto_20210621_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='0', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.CharField(default='0', max_length=50)),
                ('mobile_number', models.CharField(default='0', max_length=12)),
                ('address', models.CharField(default='0', max_length=50)),
                ('doctors', models.FileField(default='0', upload_to='media/doctors')),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
