# Generated by Django 3.1.7 on 2021-06-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0016_patient_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_profile',
            name='doctors',
        ),
        migrations.AddField(
            model_name='patient_profile',
            name='patients',
            field=models.FileField(default='0', upload_to='media/patients'),
        ),
    ]
