# Generated by Django 3.1.7 on 2021-07-12 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0018_auto_20210624_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(default='0', max_length=20)),
                ('patient_name', models.CharField(default='0', max_length=20)),
                ('appt_date', models.DateField(blank=True, null=True)),
                ('time_slot', models.TimeField()),
                ('dr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsite.doctor_profile')),
                ('pt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsite.patient_profile')),
            ],
        ),
        migrations.DeleteModel(
            name='doctor',
        ),
        migrations.DeleteModel(
            name='hospital_head',
        ),
    ]
