# Generated by Django 3.1.7 on 2021-07-15 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mywebsite', '0020_auto_20210715_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='pt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
