# Generated by Django 3.1.7 on 2021-07-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0021_auto_20210715_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
